POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "name": "vietcong",
    "email": "vietcong@gmail.com",
    "password": "vietcong",
    "role": "admin"
}


###

POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "vietcong@gmail.com",
    "password": "vietcong"
}